// Specs dos diagramas de arquitetura (um por projeto). Sem nomes reais (SPEC §8).
// Coordenadas: centro do nó, canvas 960×540. Colunas usuais: 120 · 300 · 480 · 660 · 840.

export const specs = {
  'api-segura-banco-privado': {
    title: 'API pública, banco privado',
    subtitle: 'Só o proxy fala com a internet; o banco só aceita o Security Group do proxy.',
    groups: [{ x: 430, y: 130, w: 500, h: 330, label: 'AWS VPC' }],
    nodes: {
      partner: { x: 95, y: 290, label: 'Parceiro', sub: 'IPs fixos', kind: 'ext', w: 130 },
      dns: { x: 300, y: 290, label: 'DNS', sub: 'A · DNS only', kind: 'ext', w: 130 },
      proxy: { x: 540, y: 290, label: 'EC2 Ubuntu', sub: 'Nginx + TLS', kind: 'aws' },
      erp: { x: 800, y: 200, label: 'EC2 Windows', sub: 'ERP legado', kind: 'app' },
      db: { x: 800, y: 390, label: 'Firebird', sub: 'TCP 3050', kind: 'data', w: 140 },
    },
    edges: [
      { from: 'partner', to: 'dns', label: 'HTTPS' },
      { from: 'dns', to: 'proxy', label: '443 allowlist' },
      { from: 'proxy', to: 'erp', label: '/q · /status' },
      { from: 'erp', to: 'db', label: 'SQL' },
      { from: 'proxy', to: 'db', label: 'SG→SG', dashed: true },
    ],
    note: 'SSH 22: só IP admin · 443: só IPs do parceiro · 3050: só SG do proxy',
  },

  'entrega-video-mediaconvert': {
    title: 'MP4 fast start sem mudar URL',
    subtitle: 'Otimiza milhares de vídeos no S3 e troca o arquivo por baixo da mesma key.',
    nodes: {
      orig: { x: 110, y: 180, label: 'S3', sub: 'originais .mp4', kind: 'aws', w: 140 },
      mc: { x: 330, y: 180, label: 'MediaConvert', sub: 'moov no início', kind: 'aws' },
      opt: { x: 550, y: 180, label: 'S3', sub: '_mp4_opt/', kind: 'aws', w: 140 },
      inv: { x: 790, y: 180, label: 'S3 Batch', sub: 'Invoke Lambda', kind: 'aws' },
      copy: { x: 110, y: 320, label: 'S3 Batch', sub: 'Copy', kind: 'aws', w: 140 },
      bkp: { x: 110, y: 450, label: 'S3', sub: 'backup', kind: 'data', w: 140 },
      fn: { x: 790, y: 320, label: 'AWS Lambda', sub: 'sobrescreve', kind: 'aws' },
      final: { x: 550, y: 320, label: 'S3', sub: 'mesma key, novo MP4', kind: 'data', w: 170 },
      cf: { x: 550, y: 450, label: 'CloudFront', sub: 'Origin Shield', kind: 'aws' },
      client: { x: 320, y: 450, label: 'CRM · site', sub: 'URLs intactas', kind: 'user' },
    },
    edges: [
      { from: 'orig', to: 'mc', label: '1 job/vídeo' },
      { from: 'mc', to: 'opt' },
      { from: 'opt', to: 'inv', label: 'manifest' },
      { from: 'orig', to: 'copy' },
      { from: 'copy', to: 'bkp' },
      { from: 'inv', to: 'fn' },
      { from: 'fn', to: 'final', label: 'copy_object' },
      { from: 'final', to: 'cf' },
      { from: 'cf', to: 'client' },
    ],
    note: 'Rollback = Batch Copy invertido (backup → original).',
  },

  'ptax-lambda-terraform': {
    title: 'PTAX diária: Jenkins + Pentaho → Lambda',
    subtitle: 'Um job de 5 s/dia que pagava EC2 24/7 virou função agendada com IaC.',
    groups: [{ x: 250, y: 168, w: 440, h: 262, label: 'VPC privada' }],
    nodes: {
      sched: { x: 120, y: 220, label: 'EventBridge', sub: 'seg–sex 18:05 BRT', kind: 'aws', w: 170 },
      fn: { x: 380, y: 220, label: 'AWS Lambda', sub: 'Python · ARM64', kind: 'aws' },
      sm: { x: 380, y: 350, label: 'Secrets Manager', sub: 'KMS', kind: 'aws', w: 170 },
      db: { x: 590, y: 350, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 140 },
      bcb: { x: 600, y: 120, label: 'API PTAX', sub: 'Banco Central', kind: 'ext', w: 150 },
      sns: { x: 830, y: 220, label: 'SNS', sub: 'e-mail', kind: 'aws', w: 130 },
      cw: { x: 830, y: 350, label: 'CloudWatch', sub: 'logs', kind: 'aws', w: 150 },
      gh: { x: 120, y: 450, label: 'Terraform', sub: 'GitHub Actions', kind: 'app', w: 170 },
    },
    edges: [
      { from: 'sched', to: 'fn', label: 'invoke' },
      { from: 'fn', to: 'sm', label: 'secret' },
      { from: 'fn', to: 'db', label: 'INSERT' },
      { from: 'fn', to: 'sns', label: 'resultado' },
      { from: 'fn', to: 'bcb', label: 'HTTPS via NAT', dashed: true },
      { from: 'sns', to: 'cw', dashed: true },
      { from: 'gh', to: 'sched', label: 'apply', dashed: true },
    ],
    note: 'Janela dinâmica: MAX(DATA) no banco → idempotente. Custo ~R$ 3/mês.',
  },

  'salesforce-cdc-eventbridge': {
    title: 'CRM → ERP em ~3 segundos',
    subtitle: 'O Salesforce avisa quando muda; ninguém mais pergunta uma vez por dia.',
    nodes: {
      sf: { x: 110, y: 180, label: 'Salesforce', sub: 'CDC + Event Relay', kind: 'ext', w: 160 },
      eb: { x: 340, y: 180, label: 'EventBridge', sub: 'partner bus', kind: 'aws' },
      fn: { x: 570, y: 180, label: 'AWS Lambda', sub: 'em VPC', kind: 'aws' },
      db: { x: 810, y: 180, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 150 },
      dlq: { x: 340, y: 320, label: 'SQS', sub: 'DLQ · 14 dias', kind: 'aws' },
      sm: { x: 570, y: 320, label: 'Secrets Manager', sub: 'FB + OAuth', kind: 'aws', w: 170 },
      api: { x: 810, y: 320, label: 'API Salesforce', sub: 'SOQL complementar', kind: 'ext', w: 170 },
      cw: { x: 340, y: 450, label: 'CloudWatch', sub: 'alarme DLQ > 0', kind: 'aws' },
      sns: { x: 570, y: 450, label: 'SNS', sub: 'e-mail', kind: 'aws' },
    },
    edges: [
      { from: 'sf', to: 'eb', label: 'evento' },
      { from: 'eb', to: 'fn', label: 'regra' },
      { from: 'fn', to: 'db', label: 'UPDATE' },
      { from: 'eb', to: 'dlq', label: 'falhou', dashed: true },
      { from: 'fn', to: 'sm' },
      { from: 'fn', to: 'api', label: 'via NAT', dashed: true },
      { from: 'dlq', to: 'cw' },
      { from: 'cw', to: 'sns' },
    ],
    note: 'Medido ponta a ponta: 2,7 s. ~500 eventos/mês ≈ US$ 1,50.',
  },

  'sharepoint-lambda-pipeline': {
    title: 'Pátio → ERP sem servidor on-premise',
    subtitle: 'Caminho em tempo real por evento + fallback horário, mesma Lambda de sync.',
    nodes: {
      app: { x: 110, y: 180, label: 'Power Apps', sub: 'operador de pátio', kind: 'user', w: 160 },
      sp: { x: 340, y: 180, label: 'SharePoint', sub: 'lista', kind: 'ext' },
      flow: { x: 570, y: 180, label: 'Power Automate', sub: 'on create/modify', kind: 'ext', w: 170 },
      gw: { x: 810, y: 180, label: 'API Gateway', sub: 'HTTP API', kind: 'aws', w: 150 },
      sched: { x: 340, y: 320, label: 'EventBridge', sub: '1×/hora', kind: 'aws' },
      sync: { x: 570, y: 320, label: 'Lambda sync', sub: 'Graph → SQL', kind: 'aws', w: 170 },
      wrap: { x: 810, y: 320, label: 'Lambda wrapper', sub: '202 em ~200 ms', kind: 'aws', w: 150 },
      db: { x: 570, y: 450, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 170 },
      sm: { x: 810, y: 450, label: 'Secrets Manager', sub: 'Entra ID + FB', kind: 'aws', w: 150 },
      obs: { x: 340, y: 450, label: 'CloudWatch', sub: '+ SNS', kind: 'aws' },
    },
    edges: [
      { from: 'app', to: 'sp', label: 'salva' },
      { from: 'sp', to: 'flow' },
      { from: 'flow', to: 'gw', label: 'POST' },
      { from: 'gw', to: 'wrap' },
      { from: 'wrap', to: 'sync', label: 'async' },
      { from: 'sched', to: 'sync', label: 'fallback' },
      { from: 'sync', to: 'sp', label: 'Graph', dashed: true },
      { from: 'sync', to: 'db', label: 'UPDATE OR INSERT' },
      { from: 'sync', to: 'sm', dashed: true },
      { from: 'sync', to: 'obs', dashed: true },
    ],
    note: 'Antes: Jenkins + Pentaho (20 steps) a cada 10 min. Depois: ~4 s.',
  },

  'pwa-inventario-patio': {
    title: 'Inventário de pátio offline-first',
    subtitle: 'Bipa no IndexedDB, sobe em lote, e o DynamoDB Streams devolve pro ERP.',
    nodes: {
      op: { x: 110, y: 260, label: 'Operador', sub: 'PWA + IndexedDB', kind: 'user', w: 160 },
      cog: { x: 340, y: 140, label: 'Cognito', sub: 'filial no JWT', kind: 'aws' },
      gw: { x: 340, y: 260, label: 'API Gateway', sub: 'REST', kind: 'aws' },
      fn: { x: 570, y: 260, label: 'AWS Lambda', sub: '11 funções', kind: 'aws' },
      s3: { x: 570, y: 140, label: 'S3', sub: 'exports presigned', kind: 'aws' },
      ddb: { x: 810, y: 260, label: 'DynamoDB', sub: '4 tabelas', kind: 'data', w: 150 },
      st: { x: 810, y: 400, label: 'DynamoDB Streams', kind: 'aws', w: 170 },
      sync: { x: 570, y: 400, label: 'Lambda sync', sub: 'VPC · fdb', kind: 'aws' },
      erp: { x: 340, y: 400, label: 'Firebird', sub: 'ERP legado', kind: 'data' },
    },
    edges: [
      { from: 'op', to: 'cog', label: 'login', dashed: true },
      { from: 'op', to: 'gw', label: 'lote' },
      { from: 'gw', to: 'fn' },
      { from: 'fn', to: 'ddb', label: 'batch_writer' },
      { from: 'fn', to: 's3', dashed: true },
      { from: 'ddb', to: 'st' },
      { from: 'st', to: 'sync' },
      { from: 'sync', to: 'erp', label: 'UPDATE' },
    ],
    note: 'SYNC_ENABLED=false por 2 semanas antes de escrever no ERP de verdade.',
  },

  'portal-corporativo-serverless': {
    title: 'Portal interno: 10 apps, uma Lambda',
    subtitle: 'Monolito serverless com permissão por grupo Cognito e integrações legadas.',
    nodes: {
      user: { x: 105, y: 260, label: 'Colaboradores', sub: '7 grupos', kind: 'user', w: 150 },
      cf: { x: 295, y: 260, label: 'CloudFront', sub: '2 domínios', kind: 'aws', w: 150 },
      gw: { x: 490, y: 260, label: 'API Gateway', sub: 'JWT authorizer', kind: 'aws', w: 160 },
      cog: { x: 490, y: 140, label: 'Cognito', sub: 'grupo no token', kind: 'aws', w: 160 },
      mgr: { x: 690, y: 260, label: 'Lambda manager', sub: '80+ rotas', kind: 'aws', w: 160 },
      s3: { x: 690, y: 140, label: 'S3', sub: 'upload presigned', kind: 'aws', w: 160 },
      mute: { x: 875, y: 260, label: 'Lambda', sub: 'HEVC → H.264', kind: 'aws', w: 130 },
      graph: { x: 490, y: 400, label: 'Graph API', sub: 'OneDrive/SharePoint', kind: 'ext', w: 170 },
      ddb: { x: 690, y: 400, label: 'DynamoDB', sub: '5 tabelas', kind: 'data', w: 160 },
      erp: { x: 875, y: 400, label: 'ERP', sub: 'proxy REST', kind: 'data', w: 130 },
    },
    edges: [
      { from: 'user', to: 'cf' },
      { from: 'cf', to: 'gw' },
      { from: 'gw', to: 'cog', dashed: true },
      { from: 'gw', to: 'mgr' },
      { from: 'mgr', to: 's3', dashed: true },
      { from: 'mgr', to: 'mute', label: 'async' },
      { from: 'mgr', to: 'graph' },
      { from: 'mgr', to: 'ddb' },
      { from: 'mgr', to: 'erp', label: 'holerite' },
    ],
    note: '3ª Lambda: relatório diário via EventBridge + SES. Segredos no SSM. ~US$ 9/mês.',
  },

  'finops-security-bedrock': {
    title: 'FinOps + Security toda sexta',
    subtitle: 'Coleta read-only da conta, findings priorizados por impacto e severidade.',
    nodes: {
      eb: { x: 110, y: 190, label: 'EventBridge', sub: 'sexta 8h BRT', kind: 'aws', w: 150 },
      col: { x: 340, y: 190, label: 'Lambda coleta', sub: 'boto3 paralelo', kind: 'aws', w: 160 },
      rules: { x: 570, y: 190, label: 'Motor de regras', sub: '~600 linhas', kind: 'app', w: 170 },
      ddb: { x: 810, y: 190, label: 'DynamoDB', sub: 'raw + analysis', kind: 'data', w: 150 },
      apis: { x: 340, y: 330, label: 'APIs AWS', sub: 'CE · IAM · GuardDuty', kind: 'ext', w: 180 },
      llm: { x: 570, y: 330, label: 'Bedrock', sub: 'v1 · removido', kind: 'ai', w: 170 },
      api: { x: 810, y: 330, label: 'API Gateway', sub: 'token no SSM', kind: 'aws', w: 150 },
      web: { x: 810, y: 455, label: 'CloudFront + S3', sub: 'dashboard', kind: 'aws', w: 170 },
    },
    edges: [
      { from: 'eb', to: 'col' },
      { from: 'col', to: 'apis', label: 'read-only' },
      { from: 'col', to: 'rules' },
      { from: 'rules', to: 'ddb' },
      { from: 'rules', to: 'llm', label: 'v1', dashed: true },
      { from: 'api', to: 'ddb' },
      { from: 'web', to: 'api' },
    ],
    note: 'v1 com LLM: ~US$ 1,70/mês e saída variável. v2 com regras: ~US$ 0,80 e reprodutível.',
  },

  dungeonai: {
    title: 'DungeonAI: a IA como Dungeon Master',
    subtitle: 'Um agente com três tools: narrar, ilustrar a cena e salvar o estado.',
    nodes: {
      p: { x: 105, y: 270, label: 'Jogador', sub: 'Streamlit', kind: 'user', w: 140 },
      ag: { x: 330, y: 270, label: 'Strands Agent', sub: 'dungeon_master.py', kind: 'app', w: 170 },
      llm: { x: 650, y: 150, label: 'Bedrock · Claude', sub: 'narrativa + regras', kind: 'ai', w: 190 },
      img: { x: 650, y: 270, label: 'Bedrock · imagem', sub: 'cena 512×512', kind: 'ai', w: 180 },
      ddb: { x: 650, y: 390, label: 'DynamoDB', sub: 'HP · XP · inventário', kind: 'data', w: 190 },
      s3: { x: 870, y: 270, label: 'S3', sub: 'cenas', kind: 'aws', w: 110 },
    },
    edges: [
      { from: 'p', to: 'ag', label: 'ação' },
      { from: 'ag', to: 'llm', label: 'narrate_story' },
      { from: 'ag', to: 'img', label: 'generate_scene' },
      { from: 'ag', to: 'ddb', label: 'update_state' },
      { from: 'img', to: 's3' },
    ],
    note: 'Custo por sessão (~30 turnos): US$ 0,43–0,83. Código aberto no GitHub.',
  },

  'gestao-frota-ocr': {
    title: 'Frota multi-tenant com OCR de cupom',
    subtitle: 'Cada oficina só enxerga a própria frota: tenantId no JWT e no prefixo das keys.',
    nodes: {
      drv: { x: 110, y: 190, label: 'Motorista', sub: 'PWA Next.js', kind: 'user', w: 150 },
      gw: { x: 340, y: 190, label: 'API Gateway', sub: 'HTTP · throttle', kind: 'aws', w: 160 },
      fn: { x: 570, y: 190, label: 'AWS Lambda', sub: 'SST v3', kind: 'aws', w: 160 },
      ddb: { x: 810, y: 190, label: 'DynamoDB', sub: 'TENANT#… single-table', kind: 'data', w: 170 },
      s3: { x: 340, y: 330, label: 'S3', sub: 'fotos · lifecycle', kind: 'aws', w: 160 },
      ocr: { x: 570, y: 330, label: 'Textract', sub: 'AnalyzeExpense', kind: 'ai', w: 160 },
      cron: { x: 810, y: 330, label: 'EventBridge', sub: 'manutenção 10h', kind: 'aws', w: 170 },
      ses: { x: 810, y: 455, label: 'SES', sub: 'alerta por oficina', kind: 'aws', w: 170 },
    },
    edges: [
      { from: 'drv', to: 'gw' },
      { from: 'gw', to: 'fn', label: 'JWT' },
      { from: 'fn', to: 'ddb' },
      { from: 'drv', to: 's3', label: 'presigned PUT', dashed: true },
      { from: 'fn', to: 'ocr', label: 'cupom' },
      { from: 'ocr', to: 's3', dashed: true },
      { from: 'cron', to: 'ses' },
    ],
    note: 'Foto do cupom → formulário preenchido em ~3 s. Bedrock resume as observações.',
  },

  'mailbox-cleaner-m365': {
    title: 'Limpeza de caixas M365 sem throttle',
    subtitle: 'Quem move os e-mails é o próprio Exchange, não a aplicação.',
    nodes: {
      ti: { x: 110, y: 260, label: 'TI', sub: 'Next.js', kind: 'user', w: 140 },
      api: { x: 330, y: 260, label: 'FastAPI', sub: 'Python', kind: 'app', w: 150 },
      ps: { x: 560, y: 260, label: 'PowerShell', sub: 'cert app-only', kind: 'app', w: 160 },
      exo: { x: 800, y: 260, label: 'Exchange Online', sub: 'Retention Policy', kind: 'ext', w: 170 },
      graph: { x: 330, y: 140, label: 'Graph Reports', sub: 'ranking de quota', kind: 'ext', w: 170 },
      db: { x: 330, y: 400, label: 'sqlite', sub: 'jobs · poll 15 min', kind: 'data', w: 170 },
      mfa: { x: 800, y: 400, label: 'Managed Folder', sub: 'Assistant', kind: 'ext', w: 170 },
      arc: { x: 560, y: 400, label: 'Online Archive', kind: 'data', w: 160 },
    },
    edges: [
      { from: 'ti', to: 'api' },
      { from: 'graph', to: 'api', dashed: true },
      { from: 'api', to: 'ps', label: 'subprocess' },
      { from: 'ps', to: 'exo', label: 'apply' },
      { from: 'exo', to: 'mfa' },
      { from: 'mfa', to: 'arc', label: 'move' },
      { from: 'api', to: 'db' },
    ],
    note: '2 mil itens: ~13 h via EWS em lote → ~3 h server-side.',
  },

  // ── Lote 1 (Tier A novos) ──────────────────────────────────────────────

  'duckdb-salesforce': {
    title: 'Salesforce como tabela do DuckDB',
    subtitle: 'A extensão cuida de auth, transporte e pushdown; joins e Parquet ficam no DuckDB.',
    groups: [{ x: 250, y: 95, w: 410, h: 390, label: 'extensão C++ (processo do DuckDB)' }],
    nodes: {
      sql: { x: 110, y: 270, label: 'Analista', sub: 'ATTACH · SELECT', kind: 'user', w: 150 },
      cat: { x: 360, y: 160, label: 'Catálogo', sub: 'sObject → tabela', kind: 'app', w: 170 },
      qb: { x: 360, y: 270, label: 'Query builder', sub: 'SOQL + pushdown', kind: 'app', w: 170 },
      auth: { x: 360, y: 400, label: 'Auth', sub: 'OAuth · JWT · env', kind: 'app', w: 170 },
      tr: { x: 560, y: 270, label: 'Transporte', sub: 'auto: REST | Bulk', kind: 'app', w: 160 },
      quota: { x: 560, y: 400, label: 'Quota guard', sub: '/limits', kind: 'app', w: 160 },
      rest: { x: 830, y: 190, label: 'REST /query', sub: 'paginação lazy', kind: 'ext', w: 170 },
      bulk: { x: 830, y: 330, label: 'Bulk API 2.0', sub: 'CSV · PK chunking', kind: 'ext', w: 170 },
      pq: { x: 110, y: 430, label: 'Parquet · CSV', sub: 'joins locais', kind: 'data', w: 150 },
    },
    edges: [
      { from: 'sql', to: 'qb' },
      { from: 'qb', to: 'cat', dashed: true },
      { from: 'qb', to: 'tr' },
      { from: 'tr', to: 'rest', label: '< ~10 mil' },
      { from: 'tr', to: 'bulk', label: 'extração grande' },
      { from: 'tr', to: 'quota', dashed: true },
      { from: 'auth', to: 'tr', dashed: true },
      { from: 'sql', to: 'pq', label: 'COPY', dashed: true },
    ],
    note: 'Só leitura. CI em Linux, Windows e macOS arm64. Código aberto (MIT).',
  },

  'digital-twin-3d': {
    title: 'Digital Twin 3D de planta industrial',
    subtitle: 'Planta DWG + fotos de drone viram dados validados; a cena só conhece o PlantModel.',
    groups: [{ x: 490, y: 95, w: 440, h: 395, label: 'AWS (deploy via SAM)' }],
    nodes: {
      dwg: { x: 110, y: 160, label: 'DWG · drone', sub: 'planta + fotos', kind: 'ext', w: 150 },
      json: { x: 110, y: 380, label: 'JSON da planta', sub: 'zod na carga', kind: 'data', w: 150 },
      model: { x: 330, y: 270, label: 'PlantModel', sub: 'contrato único', kind: 'app', w: 150 },
      scene: { x: 330, y: 140, label: 'React Three Fiber', sub: 'LOD · cutaway · BVH', kind: 'app', w: 180 },
      ui: { x: 330, y: 410, label: 'Orbe Assistente', sub: 'parser local PT-BR', kind: 'user', w: 170 },
      cf: { x: 610, y: 160, label: 'CloudFront + S3', sub: 'OAC · CSP', kind: 'aws', w: 170 },
      api: { x: 610, y: 300, label: 'API Gateway', sub: 'JWT Entra ID', kind: 'aws', w: 170 },
      fn: { x: 830, y: 300, label: 'AWS Lambda', sub: 'arm64 · VPC', kind: 'aws', w: 160 },
      ai: { x: 830, y: 160, label: 'Bedrock', sub: 'Nova · texto e voz', kind: 'ai', w: 160 },
      ddb: { x: 830, y: 430, label: 'DynamoDB', sub: 'ativos · cópia do estoque', kind: 'data', w: 180 },
    },
    edges: [
      { from: 'dwg', to: 'json', label: 'reconstrução' },
      { from: 'json', to: 'model' },
      { from: 'model', to: 'scene' },
      { from: 'model', to: 'ui', dashed: true },
      { from: 'scene', to: 'cf', label: 'build', dashed: true },
      { from: 'ui', to: 'api', label: '/api' },
      { from: 'api', to: 'fn' },
      { from: 'fn', to: 'ddb' },
      { from: 'fn', to: 'ai', label: 'opcional', dashed: true },
    ],
    note: 'frameloop="demand": parada, a cena não renderiza. 60 fps no notebook, ~50 no iPad.',
  },

  'classificador-chapas-ia': {
    title: 'Classificador de chapas explicável',
    subtitle: 'Visão clássica acha as regiões; a IA olha só os recortes; o especialista decide.',
    nodes: {
      up: { x: 100, y: 150, label: 'Upload', sub: 'fotos de chapas', kind: 'user', w: 140 },
      q: { x: 300, y: 150, label: 'Fila', sub: 'retry · timeout', kind: 'app', w: 140 },
      cv: { x: 510, y: 150, label: 'Visão clássica', sub: 'Lab · heatmap · P1…Pn', kind: 'app', w: 180 },
      vis: { x: 760, y: 150, label: 'Bedrock · Claude', sub: 'recortes candidatos', kind: 'ai', w: 180 },
      dec: { x: 760, y: 290, label: 'Decisor', sub: 'LLM ou regras v0', kind: 'ai', w: 180 },
      exp: { x: 510, y: 290, label: 'Explicação', sub: 'classe + evidências', kind: 'app', w: 180 },
      ui: { x: 300, y: 290, label: 'Interface', sub: 'React + WebGL · SSE', kind: 'app', w: 170 },
      rev: { x: 100, y: 290, label: 'Especialista', sub: 'confirma/corrige', kind: 'user', w: 140 },
      st: { x: 300, y: 430, label: 'Store', sub: 'resultado imutável', kind: 'data', w: 170 },
      bud: { x: 760, y: 430, label: 'Orçamento', sub: 'US$/dia · US$/mês', kind: 'data', w: 180 },
    },
    edges: [
      { from: 'up', to: 'q' },
      { from: 'q', to: 'cv' },
      { from: 'cv', to: 'vis', label: 'regiões' },
      { from: 'vis', to: 'dec', label: 'achados' },
      { from: 'dec', to: 'exp' },
      { from: 'exp', to: 'ui', label: 'SSE' },
      { from: 'ui', to: 'rev' },
      { from: 'rev', to: 'st', label: 'revisão', dashed: true },
      { from: 'bud', to: 'dec', label: 'trava', dashed: true },
    ],
    note: 'Medido: ~US$ 0,027 e ~9 s por chapa. Estourou o teto → só visão clássica + regras.',
  },

  'simulador-entrevista-voz': {
    title: 'Treino de inglês por voz com IA',
    subtitle: 'O navegador transcreve; a Lambda chama o LLM e devolve a resposta já em áudio.',
    groups: [{ x: 240, y: 95, w: 700, h: 395, label: 'AWS (SST v3 · us-east-1)' }],
    nodes: {
      pwa: { x: 115, y: 270, label: 'PWA', sub: 'Web Speech · mic', kind: 'user', w: 150 },
      cog: { x: 360, y: 155, label: 'Cognito', sub: 'JWT', kind: 'aws', w: 140 },
      ws: { x: 360, y: 270, label: 'API Gateway', sub: 'WebSocket + REST', kind: 'aws', w: 170 },
      fn: { x: 580, y: 270, label: 'AWS Lambda', sub: 'orquestrador', kind: 'aws', w: 160 },
      stt: { x: 830, y: 155, label: 'Transcribe', sub: 'próximo passo', kind: 'ext', w: 150 },
      llm: { x: 830, y: 270, label: 'Bedrock · Claude', sub: 'resposta em stream', kind: 'ai', w: 170 },
      tts: { x: 830, y: 385, label: 'Polly', sub: 'voz neural', kind: 'ai', w: 150 },
      ddb: { x: 580, y: 420, label: 'DynamoDB', sub: 'sessões · relatórios', kind: 'data', w: 170 },
      s3: { x: 360, y: 420, label: 'S3', sub: 'áudio (opt-in)', kind: 'aws', w: 140 },
    },
    edges: [
      { from: 'pwa', to: 'cog', dashed: true },
      { from: 'pwa', to: 'ws', label: 'WSS' },
      { from: 'ws', to: 'fn' },
      { from: 'fn', to: 'stt', dashed: true },
      { from: 'fn', to: 'llm', label: '1 · texto' },
      { from: 'fn', to: 'tts', label: '2 · áudio' },
      { from: 'fn', to: 'ddb' },
      { from: 'fn', to: 's3', dashed: true },
    ],
    note: 'Alvo: < 1,5 s da pausa até a voz voltar. ~US$ 18/mês para 10 sessões de 30 min.',
  },

  'backup-firebird-s3-onedrive': {
    title: 'Backup Firebird: 5 saltos viraram 1',
    subtitle: 'O script roda onde o banco mora e sobe para S3 e OneDrive em paralelo.',
    groups: [{ x: 40, y: 95, w: 410, h: 310, label: 'EC2 Linux do banco' }],
    nodes: {
      cron: { x: 140, y: 175, label: 'cron', sub: '02:00 · lockfile', kind: 'app', w: 150 },
      sh: { x: 340, y: 175, label: 'backup.sh', sub: 'set -uo pipefail', kind: 'app', w: 160 },
      db: { x: 140, y: 330, label: 'Firebird', sub: '~80 GB', kind: 'data', w: 150 },
      zip: { x: 340, y: 330, label: 'zip', sub: '~80 → ~9 GB', kind: 'app', w: 160 },
      s3: { x: 640, y: 200, label: 'S3', sub: 'IAM Role · histórico', kind: 'aws', w: 180 },
      gl: { x: 860, y: 200, label: 'Glacier', sub: '> 1 TB', kind: 'aws', w: 140 },
      od: { x: 640, y: 360, label: 'OneDrive', sub: 'rclone · Graph API', kind: 'ext', w: 180 },
      org: { x: 860, y: 340, label: 'AWS Lambda', sub: 'organiza por mês', kind: 'aws', w: 150 },
      st: { x: 640, y: 470, label: '_status.txt', sub: 'sucesso ou falha', kind: 'data', w: 180 },
    },
    edges: [
      { from: 'cron', to: 'sh' },
      { from: 'db', to: 'zip' },
      { from: 'sh', to: 'zip', dashed: true },
      { from: 'zip', to: 's3', label: 'aws s3 cp' },
      { from: 'zip', to: 'od', label: 'rclone copy' },
      { from: 'od', to: 'st', label: 'trap EXIT', dashed: true },
      { from: 's3', to: 'gl', dashed: true },
      { from: 'org', to: 's3', dashed: true },
    ],
    note: 'Regra 3-2-1: AWS e Microsoft isolados. OneDrive guarda só os 10 últimos.',
  },

  // ── Lote 2 ─────────────────────────────────────────────────────────────

  'novidades-aws-ptbr': {
    title: 'Novidades da AWS em PT-BR, todo dia',
    subtitle: 'Um cron, uma Lambda e um LLM barato viram um site estático traduzido.',
    nodes: {
      cron: { x: 110, y: 160, label: 'EventBridge', sub: 'cron 08:00 BRT', kind: 'aws', w: 160 },
      fn: { x: 360, y: 270, label: 'AWS Lambda', sub: 'Python 3.12', kind: 'aws', w: 160 },
      rss: { x: 110, y: 380, label: 'What’s New', sub: 'RSS + página', kind: 'ext', w: 160 },
      ddb: { x: 360, y: 430, label: 'DynamoDB', sub: 'dedup · TTL 30 d', kind: 'data', w: 160 },
      llm: { x: 620, y: 160, label: 'Bedrock · Claude', sub: 'Haiku · JSON', kind: 'ai', w: 180 },
      san: { x: 620, y: 300, label: 'Sanitizador', sub: 'allowlist de tags', kind: 'app', w: 180 },
      s3: { x: 850, y: 300, label: 'S3 website', sub: 'index + posts', kind: 'aws', w: 150 },
      user: { x: 850, y: 430, label: 'Leitor', sub: 'HTML estático', kind: 'user', w: 150 },
    },
    edges: [
      { from: 'cron', to: 'fn', label: 'invoke' },
      { from: 'rss', to: 'fn', label: 'itens' },
      { from: 'fn', to: 'ddb', label: 'já vi?' },
      { from: 'fn', to: 'llm', label: 'traduz + categoriza' },
      { from: 'llm', to: 'san' },
      { from: 'san', to: 's3', label: 'PUT' },
      { from: 's3', to: 'user' },
    ],
    note: 'Só itens novos vão para o LLM. Custo estimado: < US$ 2/mês.',
  },

  'simulador-pedra-ambientes': {
    title: 'Pedra natural no seu ambiente, por IA',
    subtitle: 'Foto do cliente + textura da chapa → imagem editada, sem tocar no piso.',
    nodes: {
      user: { x: 110, y: 270, label: 'Cliente', sub: 'foto do ambiente', kind: 'user', w: 160 },
      ui: { x: 330, y: 270, label: 'Next.js', sub: '3 passos · resize', kind: 'app', w: 160 },
      api: { x: 560, y: 270, label: 'Rota de API', sub: 'Node · rate limit', kind: 'app', w: 170 },
      img: { x: 560, y: 420, label: 'Proxy /api/img', sub: 'catálogo · same-origin', kind: 'app', w: 190 },
      cdn: { x: 830, y: 420, label: 'Origem dos assets', sub: 'só o servidor vê', kind: 'ext', w: 180 },
      gem: { x: 830, y: 270, label: 'Gemini', sub: 'edição de imagem', kind: 'ai', w: 160 },
      tex: { x: 330, y: 130, label: 'Textura', sub: 'catálogo ou upload', kind: 'data', w: 170 },
    },
    edges: [
      { from: 'user', to: 'ui' },
      { from: 'tex', to: 'ui', dashed: true },
      { from: 'ui', to: 'api', label: 'foto + textura' },
      { from: 'api', to: 'gem', label: '1K · 2K · 4K' },
      { from: 'api', to: 'img', dashed: true },
      { from: 'img', to: 'cdn' },
    ],
    note: 'Sem AWS: roda em qualquer host Node. 6 renders/min por IP.',
  },

  'nexus-orquestrador-agentes': {
    title: 'Nexus: canvas de agentes no desktop',
    subtitle: 'Um orquestrador delega a agentes reais por adaptadores nativos; nada na tela é inventado.',
    groups: [{ x: 40, y: 95, w: 560, h: 395, label: 'Electron (processo main)' }],
    nodes: {
      ui: { x: 150, y: 175, label: 'Canvas', sub: 'React Flow · Monaco', kind: 'user', w: 180 },
      orc: { x: 150, y: 320, label: 'Orquestrador', sub: 'spec → tarefas', kind: 'app', w: 180 },
      cap: { x: 430, y: 175, label: 'Capacidades', sub: 'declaradas por agente', kind: 'app', w: 190 },
      ad: { x: 430, y: 320, label: 'Adaptadores', sub: 'eventos reais', kind: 'app', w: 190 },
      wt: { x: 150, y: 440, label: 'git worktree', sub: '1 por tarefa', kind: 'data', w: 180 },
      db: { x: 430, y: 440, label: 'node:sqlite', sub: '+ Markdown no repo', kind: 'data', w: 190 },
      cc: { x: 800, y: 175, label: 'Claude Code', sub: 'Agent SDK', kind: 'ai', w: 170 },
      cx: { x: 800, y: 300, label: 'Codex', sub: 'app-server JSON-RPC', kind: 'ai', w: 170 },
      ag: { x: 800, y: 425, label: 'Antigravity', sub: 'stream-json', kind: 'ai', w: 170 },
    },
    edges: [
      { from: 'ui', to: 'orc', label: 'pedido' },
      { from: 'orc', to: 'ad', label: 'delega' },
      { from: 'ad', to: 'cap', dashed: true },
      { from: 'cap', to: 'ui', label: '✓ ✗ ⚠', dashed: true },
      { from: 'orc', to: 'wt', dashed: true },
      { from: 'ad', to: 'db', dashed: true },
      { from: 'ad', to: 'cc' },
      { from: 'ad', to: 'cx' },
      { from: 'ad', to: 'ag' },
    ],
    note: 'Sem ACP: cada CLI pela interface mais rica que ela oferece. Instalador NSIS ~118 MB.',
  },

  'relatorio-financeiro-excel-lambda': {
    title: 'Relatório financeiro diário em Excel',
    subtitle: 'Uma Lambda consulta o ERP, monta o .xlsx formatado e manda o link por e-mail.',
    groups: [{ x: 250, y: 120, w: 450, h: 330, label: 'VPC' }],
    nodes: {
      cron: { x: 120, y: 200, label: 'EventBridge', sub: 'cron 08:00 BRT', kind: 'aws', w: 160 },
      fn: { x: 380, y: 200, label: 'AWS Lambda', sub: 'Python · openpyxl', kind: 'aws', w: 170 },
      sm: { x: 380, y: 370, label: 'Secrets Manager', sub: 'credenciais', kind: 'aws', w: 170 },
      db: { x: 590, y: 370, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 150 },
      s3: { x: 820, y: 200, label: 'S3', sub: '.xlsx · lifecycle 90 d', kind: 'aws', w: 170 },
      ses: { x: 820, y: 350, label: 'SES', sub: 'resumo + link', kind: 'aws', w: 170 },
      fin: { x: 820, y: 470, label: 'Financeiro', sub: 'presigned 7 dias', kind: 'user', w: 170 },
    },
    edges: [
      { from: 'cron', to: 'fn' },
      { from: 'fn', to: 'sm' },
      { from: 'fn', to: 'db', label: '~74 mil linhas' },
      { from: 'fn', to: 's3', label: '~15 MB' },
      { from: 'fn', to: 'ses' },
      { from: 'ses', to: 'fin' },
    ],
    note: 'Planilha com abas Resumo (KPIs) e Detalhe (filtros, datas e moeda reais).',
  },

  'conciliacao-nfse': {
    title: 'Conciliação de NFS-e: API fiscal × ERP',
    subtitle: 'Acha as notas de serviço que existem na API fiscal mas ainda não foram lançadas.',
    groups: [{ x: 470, y: 110, w: 460, h: 360, label: 'AWS (SAM)' }],
    nodes: {
      op: { x: 110, y: 270, label: 'Operadora', sub: 'React + Cloudscape', kind: 'user', w: 170 },
      cf: { x: 330, y: 270, label: 'CloudFront', sub: '/api/* · S3', kind: 'aws', w: 150 },
      api: { x: 580, y: 180, label: 'API Gateway', sub: 'HTTP · JWT', kind: 'aws', w: 160 },
      fn: { x: 580, y: 340, label: 'AWS Lambda', sub: 'Node · VPC', kind: 'aws', w: 160 },
      rec: { x: 810, y: 180, label: 'Motor', sub: 'exato → fuzzy', kind: 'app', w: 160 },
      db: { x: 810, y: 340, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 160 },
      fis: { x: 330, y: 430, label: 'API fiscal', sub: 'NFS-e ABRASF', kind: 'ext', w: 160 },
    },
    edges: [
      { from: 'op', to: 'cf' },
      { from: 'cf', to: 'api' },
      { from: 'api', to: 'fn' },
      { from: 'fn', to: 'db', label: 'lançadas' },
      { from: 'fn', to: 'fis', label: 'emitidas · cache 15 min' },
      { from: 'fn', to: 'rec' },
    ],
    note: 'Resultado: lista "a lançar" que antes saía comparando dois Excel na mão.',
  },

  // ── Lote 3 (Tier B) ────────────────────────────────────────────────────

  'consulta-nfe-api-fiscal': {
    title: 'Consulta de NF-e sem abrir o site',
    subtitle: 'Um proxy esconde as chaves, parseia o XML e guarda tudo num SQLite local para busca rápida.',
    nodes: {
      user: { x: 120, y: 270, label: 'Fiscal', sub: 'navegador', kind: 'user', w: 150 },
      web: { x: 340, y: 270, label: 'React', sub: 'Cloudscape · tabela', kind: 'app', w: 170 },
      api: { x: 590, y: 270, label: 'Express', sub: 'proxy · parser XML', kind: 'app', w: 180 },
      fis: { x: 840, y: 270, label: 'API fiscal', sub: 'NF-e · cursor 50', kind: 'ext', w: 160 },
      env: { x: 840, y: 420, label: '.env', sub: 'id + chave da conta', kind: 'data', w: 180 },
      db: { x: 590, y: 420, label: 'SQLite', sub: 'node:sqlite · upsert', kind: 'data', w: 180 },
    },
    edges: [
      { from: 'user', to: 'web' },
      { from: 'web', to: 'api', label: '/api/nfe' },
      { from: 'api', to: 'fis', label: 'headers' },
      { from: 'env', to: 'api', dashed: true },
      { from: 'api', to: 'db', label: 'sync' },
    ],
    note: 'Sync percorre a API uma vez; busca e filtros leem do banco local. Chave nunca vai ao navegador.',
  },

  'controle-vida-util-insumos': {
    title: 'Vida útil de insumos de máquina',
    subtitle: 'Horímetro atual → situação de cada peça contra a garantia do fabricante.',
    groups: [{ x: 450, y: 110, w: 480, h: 360, label: 'AWS (SST v3 · OpenNext)' }],
    nodes: {
      op: { x: 120, y: 270, label: 'Operação', sub: 'celular · desktop', kind: 'user', w: 160 },
      entra: { x: 330, y: 150, label: 'Entra ID', sub: 'login + allowlist', kind: 'ext', w: 160 },
      cf: { x: 570, y: 270, label: 'CloudFront', sub: 'Next.js', kind: 'aws', w: 160 },
      fn: { x: 800, y: 270, label: 'AWS Lambda', sub: 'rotas de API', kind: 'aws', w: 160 },
      ddb: { x: 800, y: 410, label: 'DynamoDB', sub: 'TROCA# · AUDIT#', kind: 'data', w: 170 },
      cfg: { x: 570, y: 410, label: 'machines.ts', sub: 'garantia por rolo', kind: 'data', w: 170 },
    },
    edges: [
      { from: 'op', to: 'entra', dashed: true },
      { from: 'op', to: 'cf' },
      { from: 'cf', to: 'fn' },
      { from: 'fn', to: 'ddb' },
      { from: 'cfg', to: 'fn', dashed: true },
    ],
    note: 'OK · Atenção (≥ 80% da garantia) · Vencida. Toda troca e exclusão vai para a auditoria.',
  },

  'ordens-compra-lote-erp': {
    title: 'Ordens de compra do ano, em lote',
    subtitle: 'Gera N ordens mensais no ERP legado com idempotência e retry só do que falhou.',
    groups: [{ x: 470, y: 110, w: 460, h: 360, label: 'VPC' }],
    nodes: {
      ti: { x: 110, y: 200, label: 'Compras de TI', sub: 'SPA Vite + React', kind: 'user', w: 170 },
      portal: { x: 330, y: 300, label: 'Portal', sub: 'login Microsoft · SigV4', kind: 'app', w: 180 },
      fn: { x: 590, y: 200, label: 'AWS Lambda', sub: 'Function URL · IAM', kind: 'aws', w: 180 },
      sm: { x: 590, y: 380, label: 'Secrets Manager', sub: 'Srp256 + wire crypt', kind: 'aws', w: 180 },
      db: { x: 830, y: 300, label: 'Firebird', sub: 'ERP legado', kind: 'data', w: 150 },
      s3: { x: 330, y: 440, label: 'S3', sub: 'build da SPA', kind: 'aws', w: 150 },
    },
    edges: [
      { from: 'ti', to: 'portal' },
      { from: 'portal', to: 'fn', label: 'assinado' },
      { from: 'fn', to: 'sm', dashed: true },
      { from: 'fn', to: 'db', label: '1 transação/OC' },
      { from: 'fn', to: 's3', dashed: true },
    ],
    note: 'Chave de idempotência gravada no log da OC: reenviar devolve a mesma ordem, não uma nova.',
  },

  'painel-producao-diaria': {
    title: 'Painel diário de produção',
    subtitle: 'O PCP lança chapas boas e reprocessos por máquina; o painel calcula metas e médias.',
    groups: [{ x: 450, y: 110, w: 480, h: 360, label: 'AWS (SST v3 · OpenNext)' }],
    nodes: {
      pcp: { x: 120, y: 270, label: 'Analista PCP', sub: 'lançamento diário', kind: 'user', w: 170 },
      entra: { x: 330, y: 150, label: 'Entra ID', sub: 'conta corporativa', kind: 'ext', w: 160 },
      cf: { x: 570, y: 270, label: 'CloudFront', sub: 'Next.js', kind: 'aws', w: 160 },
      fn: { x: 800, y: 270, label: 'AWS Lambda', sub: 'cálculo do painel', kind: 'aws', w: 160 },
      ddb: { x: 800, y: 410, label: 'DynamoDB', sub: 'ENTRY · MACHINE · AUDIT', kind: 'data', w: 200 },
      meta: { x: 570, y: 410, label: 'Metas', sub: 'versionadas por vigência', kind: 'data', w: 190 },
    },
    edges: [
      { from: 'pcp', to: 'entra', dashed: true },
      { from: 'pcp', to: 'cf' },
      { from: 'cf', to: 'fn' },
      { from: 'fn', to: 'ddb' },
      { from: 'meta', to: 'fn', dashed: true },
    ],
    note: 'Mudar a meta cria nova vigência: relatórios antigos não são reescritos.',
  },

  'extensao-navegador-voz': {
    title: 'Navegador controlado por voz',
    subtitle: 'Parser local resolve quase tudo em < 1 ms; o LLM só escolhe entre opções fechadas.',
    nodes: {
      mic: { x: 110, y: 270, label: 'Voz', sub: 'reconhecimento do Chrome', kind: 'user', w: 180 },
      parser: { x: 350, y: 200, label: 'Parser local', sub: '< 1 ms · PT-BR', kind: 'app', w: 170 },
      llm: { x: 350, y: 380, label: 'LLM de decisão', sub: 'opções fechadas', kind: 'ai', w: 170 },
      act: { x: 600, y: 270, label: 'Ação', sub: 'validada', kind: 'app', w: 150 },
      tab: { x: 840, y: 160, label: 'Página / abas', sub: 'content script', kind: 'ext', w: 170 },
      win: { x: 840, y: 380, label: 'Windows', sub: 'native host (opcional)', kind: 'ext', w: 180 },
    },
    edges: [
      { from: 'mic', to: 'parser', label: 'frase' },
      { from: 'parser', to: 'llm', label: 'não entendi', dashed: true },
      { from: 'parser', to: 'act' },
      { from: 'llm', to: 'act' },
      { from: 'act', to: 'tab' },
      { from: 'act', to: 'win', dashed: true },
    ],
    note: 'Nada de áudio gravado. Ao LLM vão só a frase, o site e rótulos curtos dos botões visíveis.',
  },

  // ── Lote 4 (Tier B) ────────────────────────────────────────────────────

  'agenda-push-pwa': {
    title: 'Agenda com lembrete que insiste',
    subtitle: 'Um cron de 1 minuto dispara Web Push até a corrida ser marcada como feita.',
    groups: [{ x: 250, y: 110, w: 680, h: 360, label: 'AWS (SST v3)' }],
    nodes: {
      user: { x: 120, y: 270, label: 'Motorista', sub: 'PWA · PIN', kind: 'user', w: 160 },
      cf: { x: 360, y: 180, label: 'CloudFront + S3', sub: 'StaticSite', kind: 'aws', w: 170 },
      api: { x: 360, y: 360, label: 'API Gateway', sub: 'HTTP', kind: 'aws', w: 170 },
      fn: { x: 590, y: 360, label: 'AWS Lambda', sub: 'Hono · /rides /push', kind: 'aws', w: 180 },
      ddb: { x: 820, y: 360, label: 'DynamoDB', sub: 'RIDE · SUB · CFG', kind: 'data', w: 170 },
      cron: { x: 590, y: 180, label: 'EventBridge', sub: 'rate(1 minute)', kind: 'aws', w: 180 },
      chk: { x: 820, y: 180, label: 'AWS Lambda', sub: 'check → Web Push', kind: 'aws', w: 170 },
    },
    edges: [
      { from: 'user', to: 'cf' },
      { from: 'user', to: 'api' },
      { from: 'api', to: 'fn' },
      { from: 'fn', to: 'ddb' },
      { from: 'cron', to: 'chk' },
      { from: 'chk', to: 'ddb', dashed: true },
    ],
    note: 'Push (VAPID) 1 h antes, 15 min antes, na hora, e de novo a cada 10 min até o ✅.',
  },

  'radar-passagens-aereas': {
    title: 'Radar de passagens aéreas',
    subtitle: 'Agente local busca preço onde a nuvem é bloqueada; AWS guarda, ranqueia e avisa.',
    groups: [{ x: 290, y: 110, w: 640, h: 360, label: 'AWS' }],
    nodes: {
      pc: { x: 140, y: 190, label: 'Agente local', sub: 'Task Scheduler · 30 min', kind: 'app', w: 190 },
      src: { x: 140, y: 380, label: 'Buscador de voos', sub: 'bloqueia IP de nuvem', kind: 'ext', w: 190 },
      sch: { x: 410, y: 190, label: 'EventBridge', sub: 'Scheduler', kind: 'aws', w: 160 },
      chk: { x: 640, y: 190, label: 'AWS Lambda', sub: 'checker · ranking', kind: 'aws', w: 170 },
      ddb: { x: 640, y: 360, label: 'DynamoDB', sub: 'LATEST · BEST · HIST', kind: 'data', w: 180 },
      ses: { x: 850, y: 190, label: 'SES', sub: 'novo menor preço', kind: 'aws', w: 140 },
      pwa: { x: 850, y: 360, label: 'PWA', sub: 'CloudFront + S3', kind: 'user', w: 140 },
      api: { x: 410, y: 360, label: 'API Gateway', sub: 'x-api-key', kind: 'aws', w: 160 },
    },
    edges: [
      { from: 'pc', to: 'src', label: 'headless' },
      { from: 'pc', to: 'api', label: 'resultados' },
      { from: 'sch', to: 'chk' },
      { from: 'chk', to: 'ddb' },
      { from: 'api', to: 'ddb' },
      { from: 'chk', to: 'ses' },
      { from: 'pwa', to: 'ddb', label: 'via API', dashed: true },
    ],
    note: 'Top 5 por preço, histórico de 60 dias, estimativa com milhas. Custo: free tier.',
  },

  'monitor-casas-temporada': {
    title: 'Monitor de casas de temporada para grupo',
    subtitle: 'Busca, monitora preço e divide a conta; o grupo vota por um link público.',
    groups: [{ x: 250, y: 110, w: 680, h: 360, label: 'AWS (CDK · 1 stack)' }],
    nodes: {
      grp: { x: 120, y: 270, label: 'Grupo', sub: 'link /s/<id> · votos', kind: 'user', w: 170 },
      cf: { x: 360, y: 190, label: 'CloudFront', sub: 'OAC · CSP', kind: 'aws', w: 160 },
      api: { x: 360, y: 360, label: 'API Gateway', sub: '15 rps · /api/*', kind: 'aws', w: 160 },
      sch: { x: 590, y: 190, label: 'EventBridge', sub: 'Scheduler 1 h', kind: 'aws', w: 160 },
      wk: { x: 590, y: 360, label: 'AWS Lambda', sub: 'worker · máx 3', kind: 'aws', w: 160 },
      prov: { x: 820, y: 190, label: 'Provedor', sub: 'API de anúncios', kind: 'ext', w: 160 },
      ddb: { x: 820, y: 330, label: 'DynamoDB', sub: 'SEARCH# · PROP#', kind: 'data', w: 160 },
      ses: { x: 820, y: 440, label: 'SES', sub: 'nova casa · preço caiu', kind: 'aws', w: 170 },
    },
    edges: [
      { from: 'grp', to: 'cf' },
      { from: 'grp', to: 'api' },
      { from: 'api', to: 'wk', label: 'async' },
      { from: 'sch', to: 'wk', label: 'dispatcher' },
      { from: 'wk', to: 'prov' },
      { from: 'wk', to: 'ddb' },
      { from: 'wk', to: 'ses', dashed: true },
    ],
    note: 'Rateio por pessoa, por cota ou por peso do quarto. Histórico só quando o preço muda.',
  },

  'vitrine-serverless-chapas': {
    title: 'Vitrine serverless de chapas',
    subtitle: 'Parceiro cadastra, admin valida o preço, cliente reserva. Preço só no servidor.',
    groups: [{ x: 250, y: 110, w: 680, h: 360, label: 'AWS (SAM)' }],
    nodes: {
      cli: { x: 120, y: 180, label: 'Cliente', sub: 'vitrine · lead', kind: 'user', w: 150 },
      par: { x: 120, y: 360, label: 'Parceiro / admin', sub: 'painel', kind: 'user', w: 170 },
      cf: { x: 370, y: 270, label: 'CloudFront', sub: 'site + fotos', kind: 'aws', w: 160 },
      cog: { x: 370, y: 420, label: 'Cognito', sub: 'parceiro · admin', kind: 'aws', w: 160 },
      api: { x: 600, y: 270, label: 'API Gateway', sub: 'HTTP', kind: 'aws', w: 160 },
      fn: { x: 820, y: 270, label: 'AWS Lambda', sub: 'router único', kind: 'aws', w: 160 },
      ddb: { x: 820, y: 420, label: 'DynamoDB', sub: 'PITR · VALID#', kind: 'data', w: 160 },
      s3: { x: 600, y: 150, label: 'S3', sub: 'fotos · presigned', kind: 'aws', w: 160 },
    },
    edges: [
      { from: 'cli', to: 'cf' },
      { from: 'par', to: 'cf' },
      { from: 'par', to: 'cog', dashed: true },
      { from: 'cf', to: 'api' },
      { from: 'api', to: 'fn' },
      { from: 'fn', to: 'ddb' },
      { from: 'cf', to: 's3', dashed: true },
    ],
    note: 'Vitrine nunca expõe custo nem margem. Auditoria imutável: sem endpoint de exclusão.',
  },

  'relatorio-infra-powershell': {
    title: 'Relatório diário de infra sem prints',
    subtitle: 'PowerShell coleta por API e envia um e-mail HTML pelo Microsoft Graph.',
    groups: [{ x: 40, y: 110, w: 520, h: 360, label: 'Servidor Windows' }],
    nodes: {
      ts: { x: 150, y: 190, label: 'Task Scheduler', sub: 'diário', kind: 'app', w: 170 },
      ps: { x: 400, y: 270, label: 'PowerShell', sub: 'coleta + HTML', kind: 'app', w: 170 },
      cm: { x: 150, y: 380, label: 'Credential Manager', sub: 'segredos', kind: 'data', w: 190 },
      zbx: { x: 760, y: 150, label: 'Monitoramento', sub: 'API JSON-RPC', kind: 'ext', w: 170 },
      cam: { x: 760, y: 260, label: 'Câmeras', sub: 'RTSP → ffmpeg', kind: 'ext', w: 170 },
      bkp: { x: 760, y: 370, label: 'Pasta de backup', sub: 'existe · tamanho', kind: 'ext', w: 170 },
      graph: { x: 400, y: 430, label: 'Graph /sendMail', sub: 'app-only · 1 caixa', kind: 'ext', w: 180 },
    },
    edges: [
      { from: 'ts', to: 'ps' },
      { from: 'cm', to: 'ps', dashed: true },
      { from: 'ps', to: 'zbx' },
      { from: 'ps', to: 'cam' },
      { from: 'ps', to: 'bkp' },
      { from: 'ps', to: 'graph', label: 'e-mail' },
    ],
    note: '~15 min/dia de prints manuais → 0. Pills OK/Warn/Err no topo para ler em 3 s.',
  },
}
